import Head from 'next/head';
import CovidWarning from '../components/Home/CovidWarning';

import HomeCarousel from '../components/Home/HomeCarousel';
import SectionA from '../components/Home/SectionA';
import SectionB from '../components/Home/SectionB';
import Temoignages from '../components/Home/Temoignages';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Denis Sénéchal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeCarousel />
        <SectionA />
        <SectionB />
        <Temoignages />
        <CovidWarning />
      </main>
    </div>
  );
}
